version: "3.9"
services:
  realsense_ros2:
    privileged: true
    image: realsense-ros2:latest
    container_name: realsense_ros2
    extends:
      file: docker-compose.yml
      service: realsense_ros2
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ${DATA_DIR}:/data:rw
    command: sleep infinity