FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Set up locale
RUN apt-get update && apt-get install -y locales \
  && locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Add ROS sources (both ROS 1 and ROS 2 are built for focal)
RUN apt-get update && apt-get install -y curl gnupg lsb-release \
  && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - \
  && sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros1-latest.list' \
  && sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros2-latest.list'

# Install ROS 1 Noetic
RUN apt-get update && apt-get install -y ros-noetic-desktop-full

# Install ROS 2 Humble
RUN apt-get update && apt install -y software-properties-common
RUN add-apt-repository universe
RUN apt update && apt install curl -y && \
  ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
  curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
  && dpkg -i /tmp/ros2-apt-source.deb
RUN apt-get update && apt-get install -y ros-humble-desktop

# Source setup
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

# Install ros1_bridge
RUN apt-get update && apt-get install -y \
    ros-humble-ros1-bridge \
 && rm -rf /var/lib/apt/lists/*